# Generated by Django 4.1.3 on 2022-12-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images/')),
                ('price', models.PositiveIntegerField(max_length=6)),
                ('body', models.TextField()),
            ],
        ),
    ]
